// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

/**
 * @title ISettlementRouter
 * @notice Settlement Router Interface - x402 Extended Settlement Framework
 * @dev Provides ability to complete payment verification and business execution in a single contract call
 */
interface ISettlementRouter {
    // ===== Events =====
    
    /**
     * @notice Settlement completed event
     * @param contextKey Settlement context ID (idempotency identifier)
     * @param payer Payer address
     * @param token Token contract address
     * @param amount Amount
     * @param hook Hook contract address
     * @param salt Unique identifier for this settlement (generated by Resource Server)
     * @param payTo Final recipient address
     * @param facilitatorFee Facilitator fee amount
     */
    event Settled(
        bytes32 indexed contextKey,
        address indexed payer,
        address indexed token,
        uint256 amount,
        address hook,
        bytes32 salt,
        address payTo,
        uint256 facilitatorFee
    );
    
    /**
     * @notice Hook execution completed event
     * @param contextKey Settlement context ID
     * @param hook Hook contract address
     * @param returnData Hook return data
     */
    event HookExecuted(
        bytes32 indexed contextKey,
        address indexed hook,
        bytes returnData
    );
    
    /**
     * @notice Facilitator fee accumulated event
     * @param facilitator Facilitator address
     * @param token Token contract address
     * @param amount Accumulated fee amount
     */
    event FeeAccumulated(
        address indexed facilitator,
        address indexed token,
        uint256 amount
    );
    
    /**
     * @notice Facilitator fees claimed event
     * @param facilitator Facilitator address
     * @param token Token contract address
     * @param amount Claimed fee amount
     */
    event FeesClaimed(
        address indexed facilitator,
        address indexed token,
        uint256 amount
    );
    
    /**
     * @notice Operator approval changed event
     * @param facilitator Facilitator address
     * @param operator Operator address
     * @param approved Whether approved or revoked
     */
    event FeeOperatorSet(
        address indexed facilitator,
        address indexed operator,
        bool approved
    );
    
    // ===== Core Methods =====
    
    /**
     * @notice Settle and execute Hook (main entry)
     * @dev Atomically complete: verify commitment → verify authorization → transfer → execute business logic
     * 
     * @param token ERC-3009 token contract address
     * @param from Payer address
     * @param value Amount (atomic units)
     * @param validAfter EIP-3009 valid after timestamp
     * @param validBefore EIP-3009 expiration timestamp
     * @param nonce EIP-3009 unique nonce (32 bytes) - must equal commitment hash
     * @param signature EIP-712 signature
     * @param salt Unique identifier (32 bytes, generated by Resource Server)
     * @param payTo Final recipient address (for transparency and UI display)
     * @param facilitatorFee Facilitator fee amount (deducted from value before Hook execution)
     * @param hook Hook contract address (address(0) means no Hook)
     * @param hookData Hook parameters (encoded by resource server)
     * 
     * @dev Requirements:
     *   - nonce must equal commitment hash of all parameters
     *   - Authorization signature is valid
     *   - contextKey is unused (idempotency)
     *   - Router balance is 0 after Hook execution (no fund holding)
     */
    function settleAndExecute(
        address token,
        address from,
        uint256 value,
        uint256 validAfter,
        uint256 validBefore,
        bytes32 nonce,
        bytes calldata signature,
        bytes32 salt,
        address payTo,
        uint256 facilitatorFee,
        address hook,
        bytes calldata hookData
    ) external;
    
    // ===== Query Methods =====
    
    /**
     * @notice Check if contextKey has been settled
     * @param contextKey Settlement context ID
     * @return Whether it has been settled
     */
    function isSettled(bytes32 contextKey) external view returns (bool);
    
    /**
     * @notice Calculate contextKey
     * @param from Payer address
     * @param token Token contract address
     * @param nonce EIP-3009 nonce
     * @return contextKey
     */
    function calculateContextKey(
        address from,
        address token,
        bytes32 nonce
    ) external pure returns (bytes32);
    
    // ===== Facilitator Fee Methods =====
    
    /**
     * @notice Get pending fees for a facilitator
     * @param facilitator Facilitator address
     * @param token Token contract address
     * @return Pending fee amount
     */
    function getPendingFees(address facilitator, address token) external view returns (uint256);
    
    /**
     * @notice Claim accumulated fees for multiple tokens
     * @dev Batch claims fees to save gas. Only non-zero amounts are transferred.
     * @param tokens Array of token addresses to claim fees for
     */
    function claimFees(address[] calldata tokens) external;
    
    /**
     * @notice Set operator approval for claiming fees
     * @dev Allows operator to claim fees on behalf of the facilitator.
     *      Similar to ERC721's setApprovalForAll pattern.
     * @param operator Address to grant/revoke operator status
     * @param approved Whether to approve or revoke
     */
    function setFeeOperator(address operator, bool approved) external;
    
    /**
     * @notice Check if an address is an approved operator
     * @param facilitator The facilitator address
     * @param operator The operator address to check
     * @return Whether the operator is approved
     */
    function isFeeOperator(address facilitator, address operator) external view returns (bool);
    
    /**
     * @notice Claim accumulated fees on behalf of a facilitator
     * @dev Caller must be the facilitator or an approved operator.
     *      Allows specifying a custom recipient address for flexible fee management.
     * @param facilitator The facilitator whose fees to claim
     * @param tokens Array of token addresses to claim
     * @param recipient Address to receive the fees (if zero, sends to facilitator)
     */
    function claimFeesFor(
        address facilitator,
        address[] calldata tokens,
        address recipient
    ) external;
}

