packages:
  # X402x SDK packages
  - 'typescript/packages/*'

  # Facilitator (Production-ready component)
  - 'facilitator'

  # Examples (x402 dependency resolved via npm alias: npm:@x402x/x402@0.6.6-patch.2)
  - 'examples/showcase/server'
  - 'examples/showcase/client'

  # Website Project
  - 'web/frontend'
  - 'web/backend'

  # Applications Project
  - 'apps/xdefi-app'
