export const tokenMintABI = [
	{
		inputs: [
			{
				internalType: "address",
				name: "_settlementRouter",
				type: "address",
			},
			{ internalType: "address", name: "_x402xToken", type: "address" },
			{ internalType: "address", name: "_usdcToken", type: "address" },
			{ internalType: "address", name: "_admin", type: "address" },
			{ internalType: "uint256", name: "_P0_ud60x18", type: "uint256" },
			{ internalType: "uint256", name: "_k_ud60x18", type: "uint256" },
		],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{ inputs: [], name: "CalculationError", type: "error" },
	{ inputs: [], name: "InsufficientTokens", type: "error" },
	{ inputs: [], name: "InvalidAddress", type: "error" },
	{ inputs: [], name: "InvalidAmount", type: "error" },
	{ inputs: [], name: "InvalidToken", type: "error" },
	{ inputs: [], name: "OnlyAdmin", type: "error" },
	{ inputs: [], name: "OnlyRouter", type: "error" },
	{
		inputs: [
			{ internalType: "uint256", name: "x", type: "uint256" },
			{ internalType: "uint256", name: "y", type: "uint256" },
		],
		name: "PRBMath_MulDiv18_Overflow",
		type: "error",
	},
	{
		inputs: [{ internalType: "UD60x18", name: "x", type: "uint256" }],
		name: "PRBMath_UD60x18_Exp2_InputTooBig",
		type: "error",
	},
	{
		inputs: [{ internalType: "UD60x18", name: "x", type: "uint256" }],
		name: "PRBMath_UD60x18_Exp_InputTooBig",
		type: "error",
	},
	{
		inputs: [{ internalType: "address", name: "token", type: "address" }],
		name: "SafeERC20FailedOperation",
		type: "error",
	},
	{ inputs: [], name: "SaleCompleted", type: "error" },
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "oldAdmin",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "newAdmin",
				type: "address",
			},
		],
		name: "AdminChanged",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "admin",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
		],
		name: "TokensDeposited",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "bytes32",
				name: "contextKey",
				type: "bytes32",
			},
			{
				indexed: true,
				internalType: "address",
				name: "buyer",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "usdcAmount",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "tokensReceived",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "newPrice",
				type: "uint256",
			},
		],
		name: "TokensPurchased",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "admin",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
		],
		name: "TokensWithdrawn",
		type: "event",
	},
	{
		inputs: [],
		name: "P0",
		outputs: [{ internalType: "UD60x18", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "TOTAL_SALE_SUPPLY",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "USDC_DECIMALS",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "X402X_DECIMALS",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "admin",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "usdcAmount", type: "uint256" }],
		name: "calculateTokensForUsdc",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "tokenAmount", type: "uint256" }],
		name: "calculateUsdcForTokens",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
		name: "depositTokens",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "bytes32", name: "contextKey", type: "bytes32" },
			{ internalType: "address", name: "payer", type: "address" },
			{ internalType: "address", name: "token", type: "address" },
			{ internalType: "uint256", name: "amount", type: "uint256" },
			{ internalType: "bytes32", name: "", type: "bytes32" },
			{ internalType: "address", name: "payTo", type: "address" },
			{ internalType: "address", name: "", type: "address" },
			{ internalType: "bytes", name: "", type: "bytes" },
		],
		name: "execute",
		outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "getCurrentPrice",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "getRemainingSupply",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "getTokenBalance",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "getUsdcBalance",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "k",
		outputs: [{ internalType: "UD60x18", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "newAdmin", type: "address" }],
		name: "setAdmin",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "settlementRouter",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "tokensSold",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "totalUsdcCollected",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "usdcToken",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
		name: "withdrawTokens",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
		name: "withdrawUsdc",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "x402xToken",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
];
